blank_issues_enabled: true
contact_links:
  - name: â“ Ask a question
    url: https://github.com/orgs/open-sauced/discussions
    about: Ask questions about OpenSauced
  - name: ğŸª¿ Security
    url: mailto:security@opensauced.pizza
    about: Contact us about security concerns
